FROM node:20

WORKDIR /app

# package.json만 먼저 복사 → 캐시 최적화
COPY package*.json ./

RUN npm install

# 나머지 프론트 소스 복사
COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
